### ISSUE TITLE
PhenotypeLibrary reload required when clicking off the PL page

### ISSUE THREAD

**Issue by jhardin29** [ohdsi-studies/PhenotypeLibraryDiagnostics#1]
Expected behavior
When working in the https://data.ohdsi.org/PhenotypeLibrary/ page if you click into another webpage or application it should not be required to reload the https://data.ohdsi.org/PhenotypeLibrary/ page

Actual behavior
Go to https://data.ohdsi.org/PhenotypeLibrary/ page click into another webpage or application in order to utilize the phenotypelibrary the page requires reloading

Steps to reproduce behavior
See above. As note: I'm using Version 88.0.4324.182 (Official Build) (64-bit) of chrome.

**Comment by gowthamrao** [comment]
Probably should be part of Cohort Diagnostics. It may have already been resolved in version 3.
