### ISSUE TITLE
PL TemporalCharacterization cannot filter by covariate ID

### ISSUE THREAD

**Issue by jhardin29** [ohdsi-studies/PhenotypeLibraryDiagnostics#2]
Expected behavior
When working in the https://data.ohdsi.org/PhenotypeLibrary/ temporal characterization page if you try to enter or select the slider to a specific covariate ID to filter the column should filter to the covariate ID of interest

Actual behavior
Go to https://data.ohdsi.org/PhenotypeLibrary/ page select the temporal characterization menu item select or enter a covariate ID from the table; column doesn't filter.

**Comment by gowthamrao** [comment]
I believe it is fixed in version 3 of CohortDiagnostics DiagnosticsExplorer. Please report in CohortDiagnostics
