### ISSUE TITLE
PhenotypeLibraryDiagnostics is missing from renv lock filePhenotypeLibraryDiagnostics 

### ISSUE THREAD

**Issue by schuemie** [ohdsi-studies/PhenotypeLibraryDiagnostics#9]
[PhenotypeLibraryDiagnostics](https://github.com/ohdsi-studies/PhenotypeLibraryDiagnostics) itself is currently missing from the renv lock file. It should be added, pointing to this GitHub repo, and ideally with the ref set to the release tag.

**Comment by gowthamrao** [comment]
https://github.com/ohdsi-studies/PhenotypeLibraryDiagnostics/commit/92f29dd785ea833e6c17c4885bbcd52b0a681836
